# Generated by Django 4.2.6 on 2023-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dry_matter', models.FloatField(default=0)),
                ('crude_protein', models.FloatField(default=0)),
                ('crude_fiber', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('phosphorous', models.FloatField(default=0)),
                ('Energy', models.FloatField(default=0)),
                ('lysine', models.FloatField(default=0)),
                ('methionin', models.FloatField(default=0)),
            ],
        ),
    ]
